### PR TITLE
Move success loop out side of message handling loop.

### LINKED ISSUE #26: Error: Can't set headers after they are sent.
I've deployed my messenger app the heroku, found following error for every messenger message event.

Also the messenger bot has a significant reply delay (1+hr) about 3 mins after setting subscription.

```
2016-10-13T17:29:13.499866+00:00 app[web.1]: Error: Can't set headers after they are sent.
2016-10-13T17:29:13.499871+00:00 app[web.1]:     at ServerResponse.contentType (/app/node_modules/express/lib/response.js:552:15)
2016-10-13T17:29:13.499872+00:00 app[web.1]:     at ServerResponse.sendStatus (/app/node_modules/express/lib/response.js:340:8)
2016-10-13T17:29:13.499872+00:00 app[web.1]:     at ServerResponse.res.success (/app/node_modules/bottr/lib/response-middleware.js:5:11)
2016-10-13T17:29:13.499873+00:00 app[web.1]:     at /app/node_modules/bottr/lib/facebook-messenger-client.js:64:15
2016-10-13T17:29:13.499874+00:00 app[web.1]:     at Array.forEach (native)
2016-10-13T17:29:13.499875+00:00 app[web.1]:     at /app/node_modules/bottr/lib/facebook-messenger-client.js:60:27
2016-10-13T17:29:13.499875+00:00 app[web.1]:     at Array.forEach (native)
2016-10-13T17:29:13.499876+00:00 app[web.1]:     at FacebookMessengerClient.handleEvent (/app/node_modules/bottr/lib/facebook-messenger-client.js:59:16)
2016-10-13T17:29:13.499877+00:00 app[web.1]:     at FacebookMessengerClient.<anonymous> (/app/node_modules/bottr/lib/facebook-messenger-client.js:35:12)
2016-10-13T17:29:13.499878+00:00 app[web.1]:     at Event.next (/app/node_modules/bottr/lib/event.js:16:14)
2016-10-13T17:29:13.499878+00:00 app[web.1]:     at EventEmitter.emit (/app/node_modules/bottr/lib/event-emitter.js:28:9)
2016-10-13T17:29:13.499879+00:00 app[web.1]:     at Bot.trigger (/app/node_modules/bottr/lib/bot.js:49:26)
2016-10-13T17:29:13.499880+00:00 app[web.1]:     at Bot.handleWebhookRequest (/app/node_modules/bottr/lib/bot.js:44:8)
2016-10-13T17:29:13.499880+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

### PR DESCRIPTION
**Pull request by jcampbell05**
Fixes #26

### CODE REVIEW

File: lib/facebook-messenger-client.js [hunk 1]
```diff
@@ -70,6 +69,8 @@ FacebookMessengerClient.prototype.handleEvent = function(bot, req, res) {
       })
     })
 
+    res.success()
```
Comment (tjwudi) [inline lib/facebook-messenger-client.js]: `res.success` is actually still reachable after `res.sendStatus(400)`, no?
